### PR TITLE
First Homework

### PR DESCRIPTION
**Pull request by MutalievUtkirbek**
Hello My name is Mutaliev Utkirbek 
Here is my  homework  for the first lecture

### CODE REVIEW

**Comment by MutalievUtkirbek** [comment]
Hello Anton
I am Mutaliev Utkirbek

I have created PR a few days ago but did not get any comment or permission to merge.
if you have time can you write a comment on my PR

**Comment by MutalievUtkirbek** [comment]
the first PR may not show all code that I wrote but as you are a collaborator you can look through the repo.
don't think that I  did not do the homework just could not Create PR perfectly

**Comment by Morphine-medicine** [comment]
> show all code that I wrote but as you are a collaborator you can look through the repo.
> don't think that I did not

Sorry for delay, going to look to the repo itself

**Comment by MutalievUtkirbek** [comment]
> > show all code that I wrote but as you are a collaborator you can look through the repo.
> > don't think that I did not
> 
> Sorry for delay, going to look to the repo itself

Thank you very much

**Review by Morphine-medicine — APPROVED** [review]
Looks good, sorry for delay, was waiting for changes inside pr

**Pull request merged**
